<!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Atlas v0.3</title>
<style>
body{font-family:Arial;margin:0;background:#eef3f8;color:#172033}header{background:#0f172a;color:white;padding:18px 24px}
main{max-width:1250px;margin:25px auto;display:grid;grid-template-columns:1fr 1.15fr;gap:18px}.card{background:white;border-radius:14px;padding:20px;box-shadow:0 6px 18px rgba(0,0,0,.08)}
textarea{width:100%;height:300px;border:1px solid #cbd5e1;border-radius:10px;padding:12px}button{background:#2563eb;color:white;border:0;border-radius:8px;padding:12px 16px;font-weight:bold;margin:8px 6px 0 0;cursor:pointer}.secondary{background:#334155}
.block{background:#f8fafc;border-left:5px solid #2563eb;border-radius:10px;padding:12px;margin:10px 0}.green{border-left-color:#16a34a}.orange{border-left-color:#f59e0b}.red{border-left-color:#dc2626}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.kpi{background:#f8fafc;padding:12px;border-radius:10px}.kpi b{display:block;font-size:24px}
</style></head><body><header><h2>Atlas v0.3 — Dossier Intelligent</h2></header><main><section class="card"><h3>Déclaration / dossier</h3><input id="claimId" value="D-1001" style="width:100%;padding:10px;margin-bottom:10px;border:1px solid #cbd5e1;border-radius:8px"><textarea id="txt">Dégât des eaux le 12/06/2026 au 12 rue Victor Hugo. Fuite du voisin du dessus. Photos et devis 2350 euros.</textarea><button onclick="analyzeLocal()">Générer dossier intelligent</button><button class="secondary" onclick="loadAuto()">Exemple Auto</button><button class="secondary" onclick="loadIncomplete()">Exemple incomplet</button></section><section class="card"><h3>Fiche gestionnaire</h3><div id="out">En attente.</div></section></main>
<script>
function h(t,a){return a.some(x=>t.includes(x))}function amt(t){let m=t.match(/(\d+)\s*(€|eur|euros)/i);return m?parseInt(m[1]):null}
function run(text){let t=text.toLowerCase(),branch="UNKNOWN",type="Non identifié",conv=null,tiers="Inconnu",cause="Inconnue",origin="Inconnue";if(h(t,["fuite","eau","plafond","parquet"])){branch="MRH";type="Dégât des eaux";cause="Fuite / infiltration";if(h(t,["voisin","tiers"])){tiers="Oui";origin="Voisin / tiers";conv="IRSI"}}if(h(t,["auto","voiture","accident","véhicule","collision"])){branch="AUTO";type="Collision";cause="Choc automobile";if(h(t,["tiers","constat","percuté"])){tiers="Oui";conv="IRSA / IDA"}}let a=amt(t),missing=[];if(!h(t,["photo"]))missing.push("Photos");if(!a&&!h(t,["devis"]))missing.push("Devis / montant");if(branch==="MRH"&&!h(t,["rue","adresse"]))missing.push("Adresse du risque");if(branch==="AUTO"&&tiers==="Oui"&&!h(t,["constat"]))missing.push("Constat amiable");let complete=100-missing.length*14,conf=92-(missing.length?18:0)-(a?0:8);let exp=missing.length?"À reporter":(a&&a<=1200?"Non recommandée":a&&a<3500?"Téléexpertise":"Terrain");let set=missing.length?"Non":(a&&a<=1200?"Oui, sous validation":"À étudier");let rec=(branch==="MRH"&&tiers==="Oui"&&a&&a>1600)?"Oui, recours recommandé":(branch==="AUTO"&&tiers==="Oui"?"Selon IRSA / IDA":"Non");let path=missing.length?"Dossier incomplet":(exp==="Téléexpertise"?"Téléexpertise possible":exp==="Terrain"?"Expertise terrain recommandée":"Indemnisation directe envisageable");let actions=[];if(missing.length)actions.push("Demander : "+missing.join(", "));if(exp==="Téléexpertise")actions.push("Programmer une téléexpertise");if(exp==="Terrain")actions.push("Missionner un expert terrain");if(rec.includes("Oui"))actions.push("Préparer recours");return{branch,type,conv,tiers,cause,origin,a,missing,complete,conf,exp,set,rec,path,actions}}
function analyzeLocal(){let id=document.getElementById("claimId").value,r=run(document.getElementById("txt").value);document.getElementById("out").innerHTML=`<div class="grid"><div class="kpi"><b>${r.conf}%</b>Confiance</div><div class="kpi"><b>${r.complete}%</b>Complétude</div></div><div class="block green"><b>Dossier ${id}</b><br>${r.branch} — ${r.type}<br>Cause : ${r.cause}<br>Origine : ${r.origin}<br>Tiers : ${r.tiers}</div><div class="block"><b>Convention</b><br>${r.conv||"Non concernée"}</div><div class="block ${r.missing.length?'red':'green'}"><b>Qu'est-ce qui manque ?</b><br>${r.missing.length?r.missing.join(", "):"Aucune pièce critique manquante"}</div><div class="block orange"><b>Que dois-je faire ?</b><ul>${(r.actions.length?r.actions:["Valider la recommandation Atlas"]).map(x=>"<li>"+x+"</li>").join("")}</ul></div><div class="block"><b>Décision proposée</b><br>Parcours : ${r.path}<br>Expertise : ${r.exp}<br>Indemnisation : ${r.set}<br>Recours : ${r.rec}<br>Montant : ${r.a?r.a+" €":"Non détecté"}</div><div class="block"><b>Pourquoi ?</b><br>Atlas a identifié les circonstances, vérifié la complétude, appliqué la convention pertinente et proposé un parcours avec validation gestionnaire obligatoire.</div>`}
function loadAuto(){document.getElementById("txt").value="Accident automobile avec tiers identifié. Constat amiable, photos et devis 980 euros.";document.getElementById("claimId").value="A-2001"}function loadIncomplete(){document.getElementById("txt").value="Dégât des eaux dans la cuisine. Fuite sous évier. Pas de photos et pas encore de devis.";document.getElementById("claimId").value="D-INC-1"}
</script></body></html>